version: '3.3'

services:
  juiceshop:
    image: "bkimminich/juice-shop"
    ports: 
      - "3000:3000"
    healthcheck: 
      test:  ["CMD", "wget", "-O", "http://localhost:3000"]
      interval: 10s
      timeout: 30s
      retries: 10